export const PERMISSIONS = {
  // Products
  CREATE_PRODUCT: 'CREATE_PRODUCT',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  VIEW_PRODUCT: 'VIEW_PRODUCT',

  // Warehouses
  CREATE_WAREHOUSE: 'CREATE_WAREHOUSE',
  UPDATE_WAREHOUSE: 'UPDATE_WAREHOUSE',
  DELETE_WAREHOUSE: 'DELETE_WAREHOUSE',
  VIEW_WAREHOUSE: 'VIEW_WAREHOUSE',

  // Stock
  STOCK_INBOUND: 'STOCK_INBOUND',
  STOCK_OUTBOUND: 'STOCK_OUTBOUND',
  STOCK_ADJUSTMENT: 'STOCK_ADJUSTMENT',
  STOCK_TRANSFER: 'STOCK_TRANSFER',
  VIEW_BALANCE: 'VIEW_BALANCE',
  VIEW_MOVEMENTS: 'VIEW_MOVEMENTS',

  // Users / RBAC
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_ROLES: 'MANAGE_ROLES',

  // Audit
  VIEW_AUDIT_LOG: 'VIEW_AUDIT_LOG',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export const ALL_PERMISSIONS = Object.values(PERMISSIONS);

export const DEFAULT_ROLE_PERMISSIONS: Record<string, Permission[]> = {
  Admin: ALL_PERMISSIONS,
  Manager: [
    PERMISSIONS.CREATE_PRODUCT,
    PERMISSIONS.UPDATE_PRODUCT,
    PERMISSIONS.DELETE_PRODUCT,
    PERMISSIONS.VIEW_PRODUCT,
    PERMISSIONS.CREATE_WAREHOUSE,
    PERMISSIONS.UPDATE_WAREHOUSE,
    PERMISSIONS.VIEW_WAREHOUSE,
    PERMISSIONS.STOCK_INBOUND,
    PERMISSIONS.STOCK_OUTBOUND,
    PERMISSIONS.STOCK_ADJUSTMENT,
    PERMISSIONS.STOCK_TRANSFER,
    PERMISSIONS.VIEW_BALANCE,
    PERMISSIONS.VIEW_MOVEMENTS,
    PERMISSIONS.VIEW_AUDIT_LOG,
  ],
  Staff: [
    PERMISSIONS.VIEW_PRODUCT,
    PERMISSIONS.VIEW_WAREHOUSE,
    PERMISSIONS.STOCK_INBOUND,
    PERMISSIONS.STOCK_OUTBOUND,
    PERMISSIONS.VIEW_BALANCE,
    PERMISSIONS.VIEW_MOVEMENTS,
  ],
};
